-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT,
  points INTEGER DEFAULT 0,
  cash_balance DECIMAL(10,2) DEFAULT 0,
  total_power INTEGER DEFAULT 0,
  season_power INTEGER DEFAULT 0,
  camp TEXT CHECK (camp IN ('north', 'south')),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 话题表（支持双模式：文化差异 + 同城辩论）
CREATE TABLE IF NOT EXISTS public.topics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  debate_type TEXT NOT NULL CHECK (debate_type IN ('culture', 'local')),
  creator_id UUID REFERENCES public.profiles(id),
  camps TEXT[] NOT NULL,
  raw_votes INTEGER[] DEFAULT '{}',
  ai_boost_percents DECIMAL[] DEFAULT '{}',
  final_votes INTEGER[] DEFAULT '{}',
  total_participants INTEGER DEFAULT 0,
  heat INTEGER DEFAULT 0,
  expire_at TIMESTAMP,
  ai_boost_expire_at TIMESTAMP,
  leading_camp INTEGER DEFAULT 0,
  cover_image TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  support_pool INTEGER DEFAULT 0,
  sponsored_by UUID,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 投票记录表
CREATE TABLE IF NOT EXISTS public.votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id UUID REFERENCES public.topics(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id),
  camp_index INTEGER NOT NULL,
  points INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(topic_id, user_id)
);

-- 评论/佐证表
CREATE TABLE IF NOT EXISTS public.comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id UUID REFERENCES public.topics(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id),
  camp_index INTEGER,
  content TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  likes INTEGER DEFAULT 0,
  replies INTEGER DEFAULT 0,
  is_hot BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- AI裁判记录表
CREATE TABLE IF NOT EXISTS public.ai_judgments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id UUID REFERENCES public.topics(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id),
  content TEXT NOT NULL,
  ai_summary TEXT,
  ai_taunt TEXT,
  favored_camp INTEGER,
  boost_percent DECIMAL(5,2),
  points_cost INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 积分变动记录表
CREATE TABLE IF NOT EXISTS public.points_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id),
  reason TEXT NOT NULL,
  delta INTEGER NOT NULL,
  balance INTEGER NOT NULL,
  topic_id UUID REFERENCES public.topics(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 现金变动记录表
CREATE TABLE IF NOT EXISTS public.cash_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id),
  reason TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  balance DECIMAL(10,2) NOT NULL,
  topic_id UUID REFERENCES public.topics(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 提现申请表
CREATE TABLE IF NOT EXISTS public.withdrawals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id),
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  bank_info JSONB,
  processed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 关注关系表
CREATE TABLE IF NOT EXISTS public.follows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id UUID REFERENCES public.profiles(id),
  following_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

-- 消息通知表
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id),
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  topic_id UUID REFERENCES public.topics(id),
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 举报表
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID REFERENCES public.profiles(id),
  target_type TEXT NOT NULL,
  target_id UUID NOT NULL,
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_judgments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.points_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- 创建RLS策略
CREATE POLICY "所有人可查看公开资料" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "用户可更新自己资料" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "所有人可查看已审核话题" ON public.topics FOR SELECT USING (status = 'approved');
CREATE POLICY "用户可创建话题" ON public.topics FOR INSERT WITH CHECK (auth.uid() = creator_id);

CREATE POLICY "所有人可查看投票" ON public.votes FOR SELECT USING (true);
CREATE POLICY "用户可投票" ON public.votes FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "所有人可查看评论" ON public.comments FOR SELECT USING (true);
CREATE POLICY "用户可发表评论" ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户可查看自己积分记录" ON public.points_transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可查看自己现金记录" ON public.cash_transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可申请提现" ON public.withdrawals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可查看自己提现记录" ON public.withdrawals FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户可查看自己通知" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可标记通知已读" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户可查看关注关系" ON public.follows FOR SELECT USING (true);
CREATE POLICY "用户可关注/取关" ON public.follows FOR ALL USING (auth.uid() = follower_id);