/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  const configUrl = (window as any).MEOO_CONFIG?.meoo_app_access_url;
  if (configUrl) return `${configUrl}/sb-api`;

  const origin = location.origin;
  // Capacitor 原生环境 origin 为自定义 scheme（如 chaojiaapp://localhost），
  // 不是有效的 HTTP/HTTPS URL，需使用占位地址避免 createClient 抛异常
  if (origin && origin.startsWith('http')) {
    return `${origin}/sb-api`;
  }
  return 'https://localhost/sb-api';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc3MzY3NDUyLCJleHAiOjEzMjg4MDA3NDUyfQ.xxzHGxUXLw__rgGOQxHyhB4cC9kVaJr1BBn8AWw0ZBc';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
